services:
  - type: web
    name: resume-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: demo  # Меняем на demo вместо production
    ports:
      - port: 8000  # Добавляем явное указание порта